In [82]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

pio.templates.default = "plotly_dark"

In [83]:
df = pd.read_csv('PGA_RAW_DATA.csv')

In [84]:
df.head()

,Player_initial_last,tournament id,player id,hole_par,strokes,hole_DKP,hole_FDP,hole_SDP,streak_DKP,streak_FDP,...,purse,season,no_cut,Finish,sg_putt,sg_arg,sg_app,sg_ott,sg_t2g,sg_total
0,A. Ancer,401353224,9261,288,289,60.0,51.1,56,3,7.6,...,12.0,2022,0,T32,0.20,-0.13,-0.08,0.86,0.65,0.85
1,A. Hadwin,401353224,5548,288,286,72.5,61.5,61,8,13.0,...,12.0,2022,0,T18,0.36,0.75,0.31,0.18,1.24,1.60
2,A. Lahiri,401353224,4989,144,147,21.5,17.4,27,0,0.0,...,12.0,2022,0,CUT,-0.56,0.74,-1.09,0.37,0.02,-0.54
3,A. Long,401353224,6015,144,151,20.5,13.6,17,0,0.4,...,12.0,2022,0,CUT,-1.46,-1.86,-0.02,0.80,-1.08,-2.54
4,A. Noren,401353224,3832,144,148,23.5,18.1,23,0,1.2,...,12.0,2022,0,CUT,0.53,-0.36,-1.39,0.19,-1.56,-1.04

In [109]:
stats_df = df[df['season'] == 2022]

In [110]:
stats_df.head(5)

,hole_par,strokes,hole_DKP,hole_FDP,hole_SDP,streak_DKP,streak_FDP,streak_SDP,n_rounds,made_cut,...,course,date,season,Finish,sg_putt,sg_arg,sg_app,sg_ott,sg_t2g,sg_total
0,288,289,60.0,51.1,56,3,7.6,3,4,1,...,"Muirfield Village Golf Club - Dublin, OH",2022-06-05,2022,T32,0.2,-0.13,-0.08,0.86,0.65,0.85
1,288,286,72.5,61.5,61,8,13.0,3,4,1,...,"Muirfield Village Golf Club - Dublin, OH",2022-06-05,2022,T18,0.36,0.75,0.31,0.18,1.24,1.6
2,144,147,21.5,17.4,27,0,0.0,0,2,0,...,"Muirfield Village Golf Club - Dublin, OH",2022-06-05,2022,CUT,-0.56,0.74,-1.09,0.37,0.02,-0.54
3,144,151,20.5,13.6,17,0,0.4,0,2,0,...,"Muirfield Village Golf Club - Dublin, OH",2022-06-05,2022,CUT,-1.46,-1.86,-0.02,0.8,-1.08,-2.54
4,144,148,23.5,18.1,23,0,1.2,0,2,0,...,"Muirfield Village Golf Club - Dublin, OH",2022-06-05,2022,CUT,0.53,-0.36,-1.39,0.19,-1.56,-1.04

In [112]:
stats_2022_df = stats_df[['season', 'player', 'strokes', 'hole_par', 'course', 'tournament name']]

In [114]:
stats_2022_df.head()

,season,player,strokes,hole_par,course,tournament name
0,2022,Abraham Ancer,289,288,"Muirfield Village Golf Club - Dublin, OH",The Memorial Tournament pres. by Nationwide
1,2022,Adam Hadwin,286,288,"Muirfield Village Golf Club - Dublin, OH",The Memorial Tournament pres. by Nationwide
2,2022,Anirban Lahiri,147,144,"Muirfield Village Golf Club - Dublin, OH",The Memorial Tournament pres. by Nationwide
3,2022,Adam Long,151,144,"Muirfield Village Golf Club - Dublin, OH",The Memorial Tournament pres. by Nationwide
4,2022,Alexander Noren,148,144,"Muirfield Village Golf Club - Dublin, OH",The Memorial Tournament pres. by Nationwide

In [115]:
fig = px.scatter(stats_2022_df, x='hole_par', y='strokes', color= 'player', facet_col="course", facet_row="tournament name")

KeyboardInterrupt: